export const players = [
  {
    Name: "MS Dhoni",
    Image: "https://scores.iplt20.com/ipl/playerimages/MS%20Dhoni.png",
    Attributes: {
      Mat: 250,
      Runs: 5082,
      HS: 84,
      BtAvg: 38.79,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 142,
    },
  },
  {
    Name: "Rohit Sharma",
    Image: "https://scores.iplt20.com/ipl/playerimages/Rohit%20Sharma.png",
    Attributes: {
      Mat: 243,
      Runs: 6211,
      HS: 109,
      BtAvg: 29.57,
      Century: 1,
      Wkts: 15,
      BBI: "4/6",
      BwAvg: 30.2,
      Fifers: 0,
      Catch: 98,
    },
  },
  {
    Name: "Dinesh Karthik",
    Image: "https://scores.iplt20.com/ipl/playerimages/Dinesh%20Karthik.png",
    Attributes: {
      Mat: 242,
      Runs: 4516,
      HS: 97,
      BtAvg: 25.8,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 141,
    },
  },
  {
    Name: "Virat Kohli",
    Image: "https://scores.iplt20.com/ipl/playerimages/Virat%20Kohli.png",
    Attributes: {
      Mat: 237,
      Runs: 7263,
      HS: 113,
      BtAvg: 37.24,
      Century: 7,
      Wkts: 4,
      BBI: "2/25",
      BwAvg: 92,
      Fifers: 0,
      Catch: 106,
    },
  },
  {
    Name: "Ravindra Jadeja",
    Image: "https://scores.iplt20.com/ipl/playerimages/Ravindra%20Jadeja.png",
    Attributes: {
      Mat: 226,
      Runs: 2692,
      HS: 62,
      BtAvg: 26.39,
      Century: 0,
      Wkts: 152,
      BBI: "5/16",
      BwAvg: 29.57,
      Fifers: 1,
      Catch: 97,
    },
  },
  {
    Name: "Shikhar Dhawan",
    Image: "https://scores.iplt20.com/ipl/playerimages/Shikhar%20Dhawan.png",
    Attributes: {
      Mat: 217,
      Runs: 6617,
      HS: 106,
      BtAvg: 35.38,
      Century: 2,
      Wkts: 4,
      BBI: "1/7",
      BwAvg: 16.5,
      Fifers: 0,
      Catch: 96,
    },
  },
  {
    Name: "Suresh Raina",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/14.png",
    Attributes: {
      Mat: 205,
      Runs: 5528,
      HS: 100,
      BtAvg: 32.51,
      Century: 1,
      Wkts: 25,
      BBI: "2/0",
      BwAvg: 44.72,
      Fifers: 0,
      Catch: 109,
    },
  },
  {
    Name: "Robin Uthappa",
    Image: "https://scores.iplt20.com/ipl/playerimages/Robin%20Uthappa.png",
    Attributes: {
      Mat: 205,
      Runs: 4952,
      HS: 88,
      BtAvg: 27.51,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 92,
    },
  },
  {
    Name: "Ambati Rayudu",
    Image: "https://scores.iplt20.com/ipl/playerimages/Ambati%20Rayudu.png",
    Attributes: {
      Mat: 204,
      Runs: 4348,
      HS: 100,
      BtAvg: 28.23,
      Century: 1,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 64,
    },
  },
  {
    Name: "Ravichandran Ashwin",
    Image:
      "https://scores.iplt20.com/ipl/playerimages/Ravichandran%20Ashwin.png",
    Attributes: {
      Mat: 197,
      Runs: 714,
      HS: 50,
      BtAvg: 13.22,
      Century: 0,
      Wkts: 171,
      BBI: "4/34",
      BwAvg: 28.66,
      Fifers: 0,
      Catch: 43,
    },
  },
  {
    Name: "Kieron Pollard",
    Image: "https://scores.iplt20.com/ipl/playerimages/Kieron%20Pollard.png",
    Attributes: {
      Mat: 189,
      Runs: 3412,
      HS: 87,
      BtAvg: 28.67,
      Century: 0,
      Wkts: 69,
      BBI: "4/44",
      BwAvg: 31.59,
      Fifers: 0,
      Catch: 103,
    },
  },
  {
    Name: "AB de Villiers",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/233.png",
    Attributes: {
      Mat: 184,
      Runs: 5162,
      HS: 133,
      BtAvg: 39.7,
      Century: 3,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 118,
    },
  },
  {
    Name: "Piyush Chawla",
    Image: "https://scores.iplt20.com/ipl/playerimages/Piyush%20Chawla.png",
    Attributes: {
      Mat: 181,
      Runs: 609,
      HS: 24,
      BtAvg: 11.71,
      Century: 0,
      Wkts: 179,
      BBI: "4/17",
      BwAvg: 26.79,
      Fifers: 0,
      Catch: 41,
    },
  },
  {
    Name: "David Warner",
    Image: "https://scores.iplt20.com/ipl/playerimages/David%20Warner.png",
    Attributes: {
      Mat: 176,
      Runs: 6397,
      HS: 126,
      BtAvg: 41.53,
      Century: 4,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 81,
    },
  },
  {
    Name: "Yusuf Pathan",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/96.png",
    Attributes: {
      Mat: 174,
      Runs: 3204,
      HS: 100,
      BtAvg: 29.12,
      Century: 1,
      Wkts: 42,
      BBI: "3/20",
      BwAvg: 33.69,
      Fifers: 0,
      Catch: 43,
    },
  },
  {
    Name: "Ajinkya Rahane",
    Image: "https://scores.iplt20.com/ipl/playerimages/Ajinkya%20Rahane.png",
    Attributes: {
      Mat: 172,
      Runs: 4400,
      HS: 105,
      BtAvg: 30.98,
      Century: 2,
      Wkts: 1,
      BBI: "1/5",
      BwAvg: 5,
      Fifers: 0,
      Catch: 69,
    },
  },
  {
    Name: "Manish Pandey",
    Image: "https://scores.iplt20.com/ipl/playerimages/Manish%20Pandey.png",
    Attributes: {
      Mat: 170,
      Runs: 3808,
      HS: 114,
      BtAvg: 29.06,
      Century: 1,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 81,
    },
  },
  {
    Name: "Harbhajan Singh",
    Image: "https://scores.iplt20.com/ipl/playerimages/Harbhajan%20Singh.png",
    Attributes: {
      Mat: 163,
      Runs: 833,
      HS: 64,
      BtAvg: 15.71,
      Century: 0,
      Wkts: 150,
      BBI: "5/18",
      BwAvg: 26.86,
      Fifers: 1,
      Catch: 49,
    },
  },
  {
    Name: "Sunil Narine",
    Image: "https://scores.iplt20.com/ipl/playerimages/Sunil%20Narine.png",
    Attributes: {
      Mat: 162,
      Runs: 1046,
      HS: 75,
      BtAvg: 13.76,
      Century: 0,
      Wkts: 163,
      BBI: "5/19",
      BwAvg: 25.78,
      Fifers: 1,
      Catch: 25,
    },
  },
  {
    Name: "Dwayne Bravo",
    Image: "https://scores.iplt20.com/ipl/playerimages/Dwayne%20Bravo.png",
    Attributes: {
      Mat: 161,
      Runs: 1560,
      HS: 70,
      BtAvg: 22.6,
      Century: 0,
      Wkts: 183,
      BBI: "4/22",
      BwAvg: 23.82,
      Fifers: 0,
      Catch: 80,
    },
  },
  {
    Name: "Amit Mishra",
    Image: "https://scores.iplt20.com/ipl/playerimages/Amit%20Mishra.png",
    Attributes: {
      Mat: 161,
      Runs: 381,
      HS: 31,
      BtAvg: 11.9,
      Century: 0,
      Wkts: 173,
      BBI: "5/17",
      BwAvg: 23.84,
      Fifers: 1,
      Catch: 23,
    },
  },
  {
    Name: "Wriddhiman Saha",
    Image: "https://scores.iplt20.com/ipl/playerimages/Wriddhiman%20Saha.png",
    Attributes: {
      Mat: 161,
      Runs: 2798,
      HS: 115,
      BtAvg: 24.98,
      Century: 1,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 87,
    },
  },
  {
    Name: "Bhuvneshwar Kumar",
    Image: "https://scores.iplt20.com/ipl/playerimages/Bhuvneshwar%20Kumar.png",
    Attributes: {
      Mat: 160,
      Runs: 283,
      HS: 27,
      BtAvg: 8.84,
      Century: 0,
      Wkts: 170,
      BBI: "5/19",
      BwAvg: 25.85,
      Fifers: 2,
      Catch: 32,
    },
  },
  {
    Name: "Gautam Gambhir",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/84.png",
    Attributes: {
      Mat: 154,
      Runs: 4217,
      HS: 93,
      BtAvg: 31,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 28,
    },
  },
  {
    Name: "Sanju Samson",
    Image: "https://scores.iplt20.com/ipl/playerimages/Sanju%20Samson.png",
    Attributes: {
      Mat: 152,
      Runs: 3888,
      HS: 119,
      BtAvg: 29.23,
      Century: 3,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 76,
    },
  },
  {
    Name: "Yuzvendra Chahal",
    Image: "https://scores.iplt20.com/ipl/playerimages/Yuzvendra%20Chahal.png",
    Attributes: {
      Mat: 145,
      Runs: 37,
      HS: 8,
      BtAvg: 5.28,
      Century: 0,
      Wkts: 187,
      BBI: "5/40",
      BwAvg: 21.68,
      Fifers: 1,
      Catch: 25,
    },
  },
  {
    Name: "Shane Watson",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/227.png",
    Attributes: {
      Mat: 145,
      Runs: 3874,
      HS: 117,
      BtAvg: 30.99,
      Century: 4,
      Wkts: 92,
      BBI: "4/29",
      BwAvg: 29.15,
      Fifers: 0,
      Catch: 40,
    },
  },
  {
    Name: "Chris Gayle",
    Image: "https://scores.iplt20.com/ipl/playerimages/Chris%20Gayle.png",
    Attributes: {
      Mat: 142,
      Runs: 4965,
      HS: 175,
      BtAvg: 39.72,
      Century: 6,
      Wkts: 18,
      BBI: "3/21",
      BwAvg: 40.5,
      Fifers: 0,
      Catch: 29,
    },
  },
  {
    Name: "Umesh Yadav",
    Image: "https://scores.iplt20.com/ipl/playerimages/Umesh%20Yadav.png",
    Attributes: {
      Mat: 141,
      Runs: 196,
      HS: 24,
      BtAvg: 9.8,
      Century: 0,
      Wkts: 136,
      BBI: "4/23",
      BwAvg: 30.19,
      Fifers: 0,
      Catch: 37,
    },
  },
  {
    Name: "Parthiv Patel",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/44.png",
    Attributes: {
      Mat: 139,
      Runs: 2848,
      HS: 81,
      BtAvg: 22.6,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 69,
    },
  },
  {
    Name: "Suryakumar Yadav",
    Image: "https://scores.iplt20.com/ipl/playerimages/Suryakumar%20Yadav.png",
    Attributes: {
      Mat: 139,
      Runs: 3249,
      HS: 103,
      BtAvg: 31.85,
      Century: 1,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 64,
    },
  },
  {
    Name: "Axar Patel",
    Image: "https://scores.iplt20.com/ipl/playerimages/Axar%20Patel.png",
    Attributes: {
      Mat: 136,
      Runs: 1418,
      HS: 54,
      BtAvg: 20.55,
      Century: 0,
      Wkts: 112,
      BBI: "4/21",
      BwAvg: 30.54,
      Fifers: 0,
      Catch: 59,
    },
  },
  {
    Name: "Yuvraj Singh",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/113.png",
    Attributes: {
      Mat: 132,
      Runs: 2750,
      HS: 83,
      BtAvg: 24.77,
      Century: 0,
      Wkts: 36,
      BBI: "4/29",
      BwAvg: 29.91,
      Fifers: 0,
      Catch: 31,
    },
  },
  {
    Name: "Faf du Plessis",
    Image: "https://scores.iplt20.com/ipl/playerimages/Faf%20du%20Plessis.png",
    Attributes: {
      Mat: 130,
      Runs: 4133,
      HS: 96,
      BtAvg: 36.9,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 73,
    },
  },
  {
    Name: "Glenn Maxwell",
    Image: "https://scores.iplt20.com/ipl/playerimages/Glenn%20Maxwell.png",
    Attributes: {
      Mat: 124,
      Runs: 2719,
      HS: 95,
      BtAvg: 26.39,
      Century: 0,
      Wkts: 31,
      BBI: "2/15",
      BwAvg: 37.87,
      Fifers: 0,
      Catch: 44,
    },
  },
  {
    Name: "Mayank Agarwal",
    Image: "https://scores.iplt20.com/ipl/playerimages/Mayank%20Agarwal.png",
    Attributes: {
      Mat: 123,
      Runs: 2597,
      HS: 106,
      BtAvg: 22.98,
      Century: 1,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 56,
    },
  },
  {
    Name: "Hardik Pandya",
    Image: "https://scores.iplt20.com/ipl/playerimages/Hardik%20Pandya.png",
    Attributes: {
      Mat: 123,
      Runs: 2309,
      HS: 91,
      BtAvg: 30.38,
      Century: 0,
      Wkts: 53,
      BBI: "3/17",
      BwAvg: 33.26,
      Fifers: 0,
      Catch: 65,
    },
  },
  {
    Name: "Lasith Malinga",
    Image: "https://scores.iplt20.com/ipl/playerimages/Lasith%20Malinga.png",
    Attributes: {
      Mat: 122,
      Runs: 88,
      HS: 17,
      BtAvg: 5.5,
      Century: 0,
      Wkts: 170,
      BBI: "5/13",
      BwAvg: 19.79,
      Fifers: 1,
      Catch: 21,
    },
  },
  {
    Name: "David Miller",
    Image: "https://scores.iplt20.com/ipl/playerimages/David%20Miller.png",
    Attributes: {
      Mat: 121,
      Runs: 2714,
      HS: 101,
      BtAvg: 36.18,
      Century: 1,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 70,
    },
  },
  {
    Name: "Jasprit Bumrah",
    Image: "https://scores.iplt20.com/ipl/playerimages/Jasprit%20Bumrah.png",
    Attributes: {
      Mat: 120,
      Runs: 56,
      HS: 16,
      BtAvg: 8,
      Century: 0,
      Wkts: 145,
      BBI: "5/10",
      BwAvg: 23.3,
      Fifers: 1,
      Catch: 15,
    },
  },
  {
    Name: "Praveen Kumar",
    Image: "https://im.rediff.com/cricket/2013/apr/15praveen-kumar.jpg",
    Attributes: {
      Mat: 119,
      Runs: 340,
      HS: 34,
      BtAvg: 8.94,
      Century: 0,
      Wkts: 90,
      BBI: "3/18",
      BwAvg: 36.12,
      Fifers: 0,
      Catch: 14,
    },
  },
  {
    Name: "KL Rahul",
    Image: "https://scores.iplt20.com/ipl/playerimages/KL%20Rahul.png",
    Attributes: {
      Mat: 118,
      Runs: 4163,
      HS: 132,
      BtAvg: 46.77,
      Century: 4,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 63,
    },
  },
  {
    Name: "Sandeep Sharma",
    Image: "https://scores.iplt20.com/ipl/playerimages/Sandeep%20Sharma.png",
    Attributes: {
      Mat: 116,
      Runs: 54,
      HS: 9,
      BtAvg: 9,
      Century: 0,
      Wkts: 124,
      BBI: "4/20",
      BwAvg: 27.4,
      Fifers: 0,
      Catch: 18,
    },
  },
  {
    Name: "Naman Ojha",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/52.png",
    Attributes: {
      Mat: 113,
      Runs: 1554,
      HS: 94,
      BtAvg: 20.72,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 65,
    },
  },
  {
    Name: "Krunal Pandya",
    Image: "https://scores.iplt20.com/ipl/playerimages/Krunal%20Pandya.png",
    Attributes: {
      Mat: 113,
      Runs: 1514,
      HS: 86,
      BtAvg: 21.94,
      Century: 0,
      Wkts: 70,
      BBI: "3/14",
      BwAvg: 33.58,
      Fifers: 0,
      Catch: 43,
    },
  },
  {
    Name: "Andre Russell",
    Image: "https://scores.iplt20.com/ipl/playerimages/Andre%20Russell.png",
    Attributes: {
      Mat: 112,
      Runs: 2262,
      HS: 88,
      BtAvg: 29,
      Century: 0,
      Wkts: 96,
      BBI: "5/15",
      BwAvg: 24.48,
      Fifers: 1,
      Catch: 33,
    },
  },
  {
    Name: "Mandeep Singh",
    Image: "https://scores.iplt20.com/ipl/playerimages/Mandeep%20Singh.png",
    Attributes: {
      Mat: 111,
      Runs: 1706,
      HS: 77,
      BtAvg: 20.8,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 38,
    },
  },
  {
    Name: "Mohammed Shami",
    Image: "https://scores.iplt20.com/ipl/playerimages/Mohammed%20Shami.png",
    Attributes: {
      Mat: 110,
      Runs: 74,
      HS: 21,
      BtAvg: 5.69,
      Century: 0,
      Wkts: 127,
      BBI: "4/11",
      BwAvg: 26.86,
      Fifers: 0,
      Catch: 19,
    },
  },
  {
    Name: "Brendon McCullum",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/202.png",
    Attributes: {
      Mat: 109,
      Runs: 2880,
      HS: 158,
      BtAvg: 27.69,
      Century: 2,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 37,
    },
  },
  {
    Name: "Rashid Khan",
    Image: "https://scores.iplt20.com/ipl/playerimages/Rashid%20Khan.png",
    Attributes: {
      Mat: 109,
      Runs: 443,
      HS: 79,
      BtAvg: 13.84,
      Century: 0,
      Wkts: 139,
      BBI: "4/24",
      BwAvg: 20.75,
      Fifers: 0,
      Catch: 37,
    },
  },
  {
    Name: "Deepak Hooda",
    Image: "https://scores.iplt20.com/ipl/playerimages/Deepak%20Hooda.png",
    Attributes: {
      Mat: 107,
      Runs: 1320,
      HS: 64,
      BtAvg: 18.33,
      Century: 0,
      Wkts: 10,
      BBI: "2/16",
      BwAvg: 50.9,
      Fifers: 0,
      Catch: 50,
    },
  },
  {
    Name: "Murali Vijay",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/7.png",
    Attributes: {
      Mat: 106,
      Runs: 2619,
      HS: 127,
      BtAvg: 25.93,
      Century: 2,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 47,
    },
  },
  {
    Name: "Nitish Rana",
    Image: "https://scores.iplt20.com/ipl/playerimages/Nitish%20Rana.png",
    Attributes: {
      Mat: 105,
      Runs: 2594,
      HS: 87,
      BtAvg: 28.82,
      Century: 0,
      Wkts: 10,
      BBI: "2/11",
      BwAvg: 25.2,
      Fifers: 0,
      Catch: 24,
    },
  },
  {
    Name: "Vinay Kumar",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/166.png",
    Attributes: {
      Mat: 105,
      Runs: 310,
      HS: 26,
      BtAvg: 11.07,
      Century: 0,
      Wkts: 105,
      BBI: "4/40",
      BwAvg: 28.24,
      Fifers: 0,
      Catch: 35,
    },
  },
  {
    Name: "Virender Sehwag",
    Image:
      "https://img.bleacherreport.net/img/images/photos/002/916/407/hi-res-8ee7c505e48dbb5eb8bcf7168c2d74af_crop_exact.jpg?w=1200&h=1200&q=75",
    Attributes: {
      Mat: 104,
      Runs: 2728,
      HS: 122,
      BtAvg: 27.55,
      Century: 2,
      Wkts: 6,
      BBI: "2/18",
      BwAvg: 39.16,
      Fifers: 0,
      Catch: 34,
    },
  },
  {
    Name: "Irfan Pathan",
    Image: "https://im.rediff.com/cricket/2016/jan/25irfan1.jpg",
    Attributes: {
      Mat: 103,
      Runs: 1139,
      HS: 60,
      BtAvg: 21.49,
      Century: 0,
      Wkts: 80,
      BBI: "3/24",
      BwAvg: 33.11,
      Fifers: 0,
      Catch: 31,
    },
  },
  {
    Name: "Steven Smith",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/271.png",
    Attributes: {
      Mat: 103,
      Runs: 2485,
      HS: 101,
      BtAvg: 34.51,
      Century: 1,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 53,
    },
  },
  {
    Name: "Shreyas Iyer",
    Image: "https://scores.iplt20.com/ipl/playerimages/Shreyas%20Iyer.png",
    Attributes: {
      Mat: 101,
      Runs: 2776,
      HS: 96,
      BtAvg: 31.54,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 39,
    },
  },
  {
    Name: "Ishant Sharma",
    Image: "https://scores.iplt20.com/ipl/playerimages/Ishant%20Sharma.png",
    Attributes: {
      Mat: 101,
      Runs: 56,
      HS: 10,
      BtAvg: 9.33,
      Century: 0,
      Wkts: 82,
      BBI: "5/12",
      BwAvg: 35.45,
      Fifers: 1,
      Catch: 16,
    },
  },
  {
    Name: "Zaheer Khan",
    Image:
      "https://www.sportzpics.co.za/img-get2/I0000zv1pNcJzkRg/fit=1000x750/Zaheer-Khan.jpg",
    Attributes: {
      Mat: 100,
      Runs: 117,
      HS: 23,
      BtAvg: 8.35,
      Century: 0,
      Wkts: 102,
      BBI: "4/17",
      BwAvg: 27.27,
      Fifers: 0,
      Catch: 21,
    },
  },
  {
    Name: "Mohit Sharma",
    Image: "https://scores.iplt20.com/ipl/playerimages/Mohit%20Sharma.png",
    Attributes: {
      Mat: 100,
      Runs: 122,
      HS: 21,
      BtAvg: 8.13,
      Century: 0,
      Wkts: 119,
      BBI: "5/10",
      BwAvg: 23.78,
      Fifers: 1,
      Catch: 24,
    },
  },
  {
    Name: "Jacques Kallis",
    Image:
      "https://upload.wikimedia.org/wikipedia/commons/f/ff/Jacques_Kallis_1.jpg",
    Attributes: {
      Mat: 98,
      Runs: 2427,
      HS: 89,
      BtAvg: 28.55,
      Century: 0,
      Wkts: 65,
      BBI: "3/13",
      BwAvg: 35.27,
      Fifers: 0,
      Catch: 31,
    },
  },
  {
    Name: "Rishabh Pant",
    Image: "https://scores.iplt20.com/ipl/playerimages/Rishabh%20Pant.png",
    Attributes: {
      Mat: 98,
      Runs: 2838,
      HS: 128,
      BtAvg: 34.6,
      Century: 1,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 64,
    },
  },
  {
    Name: "Manoj Tiwary",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/89.png",
    Attributes: {
      Mat: 98,
      Runs: 1695,
      HS: 75,
      BtAvg: 28.72,
      Century: 0,
      Wkts: 1,
      BBI: "1/11",
      BwAvg: 83,
      Fifers: 0,
      Catch: 46,
    },
  },
  {
    Name: "Jos Buttler",
    Image: "https://scores.iplt20.com/ipl/playerimages/Jos%20Buttler.png",
    Attributes: {
      Mat: 96,
      Runs: 3223,
      HS: 124,
      BtAvg: 37.91,
      Century: 5,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 52,
    },
  },
  {
    Name: "Quinton de Kock",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/170.png",
    Attributes: {
      Mat: 96,
      Runs: 2907,
      HS: 140,
      BtAvg: 32.3,
      Century: 2,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 67,
    },
  },
  {
    Name: "Subramaniam Badrinath",
    Image: "https://timesofindia.indiatimes.com/photo/5702821.cms",
    Attributes: {
      Mat: 95,
      Runs: 1441,
      HS: 71,
      BtAvg: 30.65,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 16,
    },
  },
  {
    Name: "Rajat Bhatia",
    Image:
      "https://www.sportzpics.co.za/img-get2/I0000mP3.levFhKM/fit=1000x750/Rajat-Bhatia.jpg",
    Attributes: {
      Mat: 95,
      Runs: 342,
      HS: 26,
      BtAvg: 11.4,
      Century: 0,
      Wkts: 71,
      BBI: "4/15",
      BwAvg: 28.45,
      Fifers: 0,
      Catch: 25,
    },
  },
  {
    Name: "Stuart Binny",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/148.png",
    Attributes: {
      Mat: 95,
      Runs: 880,
      HS: 48,
      BtAvg: 19.13,
      Century: 0,
      Wkts: 22,
      BBI: "2/14",
      BwAvg: 34.45,
      Fifers: 0,
      Catch: 19,
    },
  },
  {
    Name: "Kedar Jadhav",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/297.png",
    Attributes: {
      Mat: 95,
      Runs: 1208,
      HS: 69,
      BtAvg: 22.37,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 31,
    },
  },
  {
    Name: "Dale Steyn",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/180.png",
    Attributes: {
      Mat: 95,
      Runs: 167,
      HS: 19,
      BtAvg: 7.59,
      Century: 0,
      Wkts: 97,
      BBI: "3/8",
      BwAvg: 25.85,
      Fifers: 0,
      Catch: 24,
    },
  },
  {
    Name: "Jaydev Unadkat",
    Image: "https://scores.iplt20.com/ipl/playerimages/Jaydev%20Unadkat.png",
    Attributes: {
      Mat: 94,
      Runs: 173,
      HS: 26,
      BtAvg: 13.3,
      Century: 0,
      Wkts: 91,
      BBI: "5/25",
      BwAvg: 31.53,
      Fifers: 2,
      Catch: 25,
    },
  },
  {
    Name: "Saurabh Tiwary",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/163.png",
    Attributes: {
      Mat: 93,
      Runs: 1494,
      HS: 61,
      BtAvg: 28.73,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 25,
    },
  },
  {
    Name: "Aaron Finch",
    Image: "https://scores.iplt20.com/ipl/playerimages/Aaron%20Finch.png",
    Attributes: {
      Mat: 92,
      Runs: 2091,
      HS: 88,
      BtAvg: 25.19,
      Century: 0,
      Wkts: 1,
      BBI: "1/11",
      BwAvg: 67,
      Fifers: 0,
      Catch: 28,
    },
  },
  {
    Name: "Dhawal Kulkarni",
    Image: "https://scores.iplt20.com/ipl/playerimages/Dhawal%20Kulkarni.png",
    Attributes: {
      Mat: 92,
      Runs: 104,
      HS: 28,
      BtAvg: 11.55,
      Century: 0,
      Wkts: 86,
      BBI: "4/14",
      BwAvg: 28.76,
      Fifers: 0,
      Catch: 22,
    },
  },
  {
    Name: "Pragyan Ojha",
    Image: "https://timesofindia.indiatimes.com/photo/5829911.cms",
    Attributes: {
      Mat: 92,
      Runs: 16,
      HS: 3,
      BtAvg: 1.33,
      Century: 0,
      Wkts: 89,
      BBI: "3/11",
      BwAvg: 26.2,
      Fifers: 0,
      Catch: 14,
    },
  },
  {
    Name: "Harshal Patel",
    Image: "https://scores.iplt20.com/ipl/playerimages/Harshal%20Patel.png",
    Attributes: {
      Mat: 92,
      Runs: 236,
      HS: 36,
      BtAvg: 9.83,
      Century: 0,
      Wkts: 111,
      BBI: "5/27",
      BwAvg: 24.07,
      Fifers: 1,
      Catch: 20,
    },
  },
  {
    Name: "Ishan Kishan",
    Image: "https://scores.iplt20.com/ipl/playerimages/Ishan%20Kishan.png",
    Attributes: {
      Mat: 91,
      Runs: 2324,
      HS: 99,
      BtAvg: 29.41,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 42,
    },
  },
  {
    Name: "Albie Morkel",
    Image:
      "https://crickettimes.com/wp-content/uploads/2019/01/Albie-Morkel.jpg",
    Attributes: {
      Mat: 91,
      Runs: 974,
      HS: 73,
      BtAvg: 24.35,
      Century: 0,
      Wkts: 85,
      BBI: "4/32",
      BwAvg: 27.7,
      Fifers: 0,
      Catch: 19,
    },
  },
  {
    Name: "Shubman Gill",
    Image: "https://scores.iplt20.com/ipl/playerimages/Shubman%20Gill.png",
    Attributes: {
      Mat: 91,
      Runs: 2790,
      HS: 129,
      BtAvg: 37.7,
      Century: 3,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 36,
    },
  },
  {
    Name: "Dwayne Smith",
    Image: "https://api.bdcrictime.com/dwayne-smith-20_04_2022.jpg",
    Attributes: {
      Mat: 91,
      Runs: 2385,
      HS: 87,
      BtAvg: 28.39,
      Century: 0,
      Wkts: 26,
      BBI: "4/8",
      BwAvg: 31.15,
      Fifers: 0,
      Catch: 41,
    },
  },
  {
    Name: "Rahul Dravid",
    Image:
      "https://bl-i.thgim.com/public/migration_catalog/article18033556.ece/alternates/FREE_1200/royals",
    Attributes: {
      Mat: 89,
      Runs: 2174,
      HS: 75,
      BtAvg: 28.23,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 18,
    },
  },
  {
    Name: "Rahul Tripathi",
    Image: "https://scores.iplt20.com/ipl/playerimages/Rahul%20Tripathi.png",
    Attributes: {
      Mat: 89,
      Runs: 2071,
      HS: 93,
      BtAvg: 27.25,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 31,
    },
  },
  {
    Name: "Trent Boult",
    Image: "https://scores.iplt20.com/ipl/playerimages/Trent%20Boult.png",
    Attributes: {
      Mat: 88,
      Runs: 69,
      HS: 17,
      BtAvg: 11.5,
      Century: 0,
      Wkts: 105,
      BBI: "4/18",
      BwAvg: 26.54,
      Fifers: 0,
      Catch: 30,
    },
  },
  {
    Name: "Ashish Nehra",
    Image:
      "https://akm-img-a-in.tosshub.com/indiatoday/images/story/201506/nehra-647_060515094713.jpg?VersionId=8YyZLkMtFXkK5WSwRiHSzEP7UStN8UU9",
    Attributes: {
      Mat: 88,
      Runs: 41,
      HS: 22,
      BtAvg: 5.85,
      Century: 0,
      Wkts: 106,
      BBI: "4/10",
      BwAvg: 23.53,
      Fifers: 0,
      Catch: 19,
    },
  },
  {
    Name: "Shardul Thakur",
    Image: "https://scores.iplt20.com/ipl/playerimages/Shardul%20Thakur.png",
    Attributes: {
      Mat: 86,
      Runs: 286,
      HS: 68,
      BtAvg: 11.91,
      Century: 0,
      Wkts: 89,
      BBI: "4/36",
      BwAvg: 28.76,
      Fifers: 0,
      Catch: 28,
    },
  },
  {
    Name: "JP Duminy",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/182.png",
    Attributes: {
      Mat: 83,
      Runs: 2029,
      HS: 78,
      BtAvg: 39.78,
      Century: 0,
      Wkts: 23,
      BBI: "4/17",
      BwAvg: 36.26,
      Fifers: 0,
      Catch: 30,
    },
  },
  {
    Name: "Eoin Morgan",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/197.png",
    Attributes: {
      Mat: 83,
      Runs: 1405,
      HS: 68,
      BtAvg: 22.66,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 36,
    },
  },
  {
    Name: "RP Singh",
    Image:
      "https://i.pinimg.com/474x/71/46/45/7146458d1f0fbe07568d71a9be8cb1b6.jpg",
    Attributes: {
      Mat: 82,
      Runs: 52,
      HS: 10,
      BtAvg: 3.46,
      Century: 0,
      Wkts: 90,
      BBI: "4/22",
      BwAvg: 25.97,
      Fifers: 0,
      Catch: 29,
    },
  },
  {
    Name: "Marcus Stoinis",
    Image: "https://scores.iplt20.com/ipl/playerimages/Marcus%20Stoinis.png",
    Attributes: {
      Mat: 82,
      Runs: 1478,
      HS: 89,
      BtAvg: 27.37,
      Century: 0,
      Wkts: 39,
      BBI: "4/15",
      BwAvg: 29.43,
      Fifers: 0,
      Catch: 20,
    },
  },
  {
    Name: "Chris Morris",
    Image:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/836.png",
    Attributes: {
      Mat: 81,
      Runs: 618,
      HS: 82,
      BtAvg: 22.07,
      Century: 0,
      Wkts: 95,
      BBI: "4/23",
      BwAvg: 24.15,
      Fifers: 0,
      Catch: 38,
    },
  },
  {
    Name: "Rahul Tewatia",
    Image: "https://scores.iplt20.com/ipl/playerimages/Rahul%20Tewatia.png",
    Attributes: {
      Mat: 81,
      Runs: 825,
      HS: 53,
      BtAvg: 25,
      Century: 0,
      Wkts: 32,
      BBI: "3/18",
      BwAvg: 34.71,
      Fifers: 0,
      Catch: 32,
    },
  },
  {
    Name: "Adam Gilchrist",
    Image: "https://timesofindia.indiatimes.com/photo/12594754.cms",
    Attributes: {
      Mat: 80,
      Runs: 2069,
      HS: 109,
      BtAvg: 27.22,
      Century: 2,
      Wkts: 1,
      BBI: "1/0",
      BwAvg: "-",
      Fifers: 0,
      Catch: 51,
    },
  },
  {
    Name: "Mahela Jayawardene",
    Image:
      "https://www.mumbaiindians.com/static-assets/waf-images/6d/3e/4f/4-3/592-444/pgpNGs8vKR.jpg",
    Attributes: {
      Mat: 80,
      Runs: 1802,
      HS: 110,
      BtAvg: 28.6,
      Century: 1,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 32,
    },
  },
  {
    Name: "Mohammed Siraj",
    Image: "https://scores.iplt20.com/ipl/playerimages/Mohammed%20Siraj.png",
    Attributes: {
      Mat: 79,
      Runs: 97,
      HS: 14,
      BtAvg: 12.12,
      Century: 0,
      Wkts: 78,
      BBI: "4/21",
      BwAvg: 29.82,
      Fifers: 0,
      Catch: 26,
    },
  },
  {
    Name: "Ashok Dinda",
    Image:
      "https://www.financialexpress.com/wp-content/uploads/2017/04/ashok-dinda.jpg?w=920",
    Attributes: {
      Mat: 78,
      Runs: 26,
      HS: 7,
      BtAvg: 2.6,
      Century: 0,
      Wkts: 69,
      BBI: "4/18",
      BwAvg: 30.04,
      Fifers: 0,
      Catch: 7,
    },
  },
  {
    Name: "Sachin Tendulkar",
    Image:
      "https://keepingscore.blogs.time.com/wp-content/uploads/sites/6/2012/05/sachin-tendulkar.jpg?w=480&h=320&crop=1",
    Attributes: {
      Mat: 78,
      Runs: 2334,
      HS: 100,
      BtAvg: 34.83,
      Century: 1,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 23,
    },
  },
  {
    Name: "Kane Williamson",
    Image: "https://scores.iplt20.com/ipl/playerimages/Kane%20Williamson.png",
    Attributes: {
      Mat: 77,
      Runs: 2101,
      HS: 89,
      BtAvg: 36.22,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 39,
    },
  },
  {
    Name: "Karun Nair",
    Image: "https://scores.iplt20.com/ipl/playerimages/Karun%20Nair.png",
    Attributes: {
      Mat: 76,
      Runs: 1496,
      HS: 83,
      BtAvg: 23.74,
      Century: 0,
      Wkts: 0,
      BBI: "-",
      BwAvg: "-",
      Fifers: 0,
      Catch: 23,
    },
  },
  {
    Name: "Siddharth Trivedi",
    Image:
      "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_800,q_50/lsci/db/PICTURES/CMS/156800/156853.jpg",
    Attributes: {
      Mat: 76,
      Runs: 42,
      HS: 9,
      BtAvg: 6,
      Century: 0,
      Wkts: 65,
      BBI: "4/25",
      BwAvg: 29.29,
      Fifers: 0,
      Catch: 14,
    },
  },
];
